### ISSUE TITLE
Geometry editor bugs when deleting structure

### ISSUE THREAD

**Issue by vitorslongo** [open-pulse/OpenPulse#259]
If you create a structure and delete it without finalizing, the editor won’t save what you create afterwards.

**Comment by lattaai4** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the GeometryDesignerWidget class to ensure structures are saved after deletion without finalizing. Added a flag to track modifications and updated relevant methods.

I also created pull request: https://github.com/open-pulse/OpenPulse/pull/260


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by andrefpf** [comment]
I could not reproduce this bug. Can you give more details?

**Comment by vitorslongo** [comment]
I couldn't either, I tried repeating the same steps I did that caused the problem and it seems to be working now.
