### ISSUE TITLE
Setting Cross Section from selected Points

### ISSUE THREAD

**Issue by atbrandao** [open-pulse/OpenPulse#29]
It would be useful to set the cross section for selected Points, instead of only for whole Entities.

This would give a greater flexibility for in-software geometry manipulation, making it easy to test slightly different geometries and seeing the result it would have on the system behavior.

**Comment by olavosilva** [comment]
@atbrandao We had some discussions about this function, and we agree that "setting for elements" will be a useful tool. In a first instance, we started the implementation by selecting Entities, because the designer can define exactly the dimensions of the components in a CAD software instead of counting elements to define a certain component. But, we agree that selecting Elements to set cross section will be a great tool for testing changes without change CAD. We will work on that. Thanks!

**Comment by olavosilva** [comment]
Ok!
