### ISSUE TITLE
Version of package requirements

### ISSUE THREAD

**Issue by atbrandao** [open-pulse/OpenPulse#34]
The package requirements that have minimum version requirement should be mentioned in the `requirements.txt` file with the information of the minimum required version, for example:

`matplotlib>=3.3.1`

I had to update the packages `matplotlib (v3.1.3 -> v3.3.1)` and `Pillow (v7.0.0 -> v7.2.0)` to run the latest version of the software. 

Ideally, in the future, I believe OpenPulse should have a setup.py script to automatically install all required packages in the correct versions as well as the software itself.

**Comment by raphaeltimbo** [comment]
Additionally, it would be good to have a __init__.py file with __version__ = ‘’ inside, so we can keep track of versions.
I recommend using semantic versioning: https://semver.org/
And for now I think the code should be in a 0.y.z version, since the code is not yet stable and is changing a lot. Later when the code is more stable a 1.0.0 version could be released.

**Comment by olavosilva** [comment]
@andrefpf @JoseLooLo

**Comment by olavosilva** [comment]
@andrefpf
